# multi-job workflow with sample data just with bash
name: multi-job-workflow
on: push
permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run job1 script
        run: |
          echo "Running job1 script"
          echo "Job1 completed"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run job2 script
        run: |
          echo "Running job2 script"
          echo "Job2 completed"